// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package inject

import (
	"github.com/google/wire"

	"github.com/Lofanmi/gobana/internal/sdk_sls"
)

var SdksSet = wire.NewSet(
	sdk_sls.NewClient,
)
