// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package inject

import (
	"github.com/google/wire"

	"github.com/Lofanmi/gobana/internal/logic"
	"github.com/Lofanmi/gobana/internal/logic/logic_aggregation_parser"
	"github.com/Lofanmi/gobana/internal/logic/logic_backend_factory"
	"github.com/Lofanmi/gobana/internal/logic/logic_log_parser"
	"github.com/Lofanmi/gobana/internal/logic/logic_lua_state"
	"github.com/Lofanmi/gobana/internal/logic/logic_qq_wry"
	"github.com/Lofanmi/gobana/internal/logic/logic_query_builder"
)

var LogicsSet = wire.NewSet(
	wire.Struct(new(logic_aggregation_parser.AggregationParser), "*"),
	wire.Bind(new(logic.AggregationParser), new(*logic_aggregation_parser.AggregationParser)),

	logic_backend_factory.NewBackendFactory,

	wire.Struct(new(logic_log_parser.LogParser), "*"),
	wire.Bind(new(logic.LogParser), new(*logic_log_parser.LogParser)),

	wire.Struct(new(logic_lua_state.LuaState), "*"),
	wire.Bind(new(logic.LuaState), new(*logic_lua_state.LuaState)),

	logic_qq_wry.NewQQWry,
	wire.Bind(new(logic.QQWry), new(*logic_qq_wry.QQWry)),

	wire.Struct(new(logic_query_builder.QueryBuilder), "*"),
	wire.Bind(new(logic.QueryBuilder), new(*logic_query_builder.QueryBuilder)),
)
