// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package inject

import (
	"github.com/google/wire"
)

var Sets = wire.NewSet(
	AppSet,
	ConfigSet,
	LogicsSet,
	ServiceSet,
)
