// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package inject

import (
	"github.com/google/wire"

	"github.com/Lofanmi/gobana/internal/app"
)

var AppSet = wire.NewSet(
	wire.Struct(new(app.Application), "*"),
)
