// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package inject

import (
	"github.com/google/wire"

	"github.com/Lofanmi/gobana/internal/svc_impls/svc_config"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_goja"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_logger"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_provider_factory"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_qq_wry"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_query_builder"
	"github.com/Lofanmi/gobana/service"
)

var ServiceSet = wire.NewSet(
	wire.Struct(new(svc_config.Service), "*"),
	wire.Bind(new(service.Config), new(*svc_config.Service)),

	wire.Struct(new(svc_goja.Service), "*"),
	wire.Bind(new(service.GoJa), new(*svc_goja.Service)),

	wire.Struct(new(svc_logger.Service), "*"),
	wire.Bind(new(service.Logger), new(*svc_logger.Service)),

	wire.Struct(new(svc_provider_factory.ProviderFactory), "*"),
	wire.Bind(new(service.ProviderFactory), new(*svc_provider_factory.ProviderFactory)),

	svc_qq_wry.NewQQWry,
	wire.Bind(new(service.QQWry), new(*svc_qq_wry.QQWry)),

	wire.Struct(new(svc_query_builder.QueryBuilder), "*"),
	wire.Bind(new(service.QueryBuilder), new(*svc_query_builder.QueryBuilder)),
)
