// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/Lofanmi/gobana/internal/app"
	"github.com/Lofanmi/gobana/internal/config"
	"github.com/Lofanmi/gobana/internal/logic/logic_backend_factory"
	"github.com/Lofanmi/gobana/internal/logic/logic_log_parser"
	"github.com/Lofanmi/gobana/internal/logic/logic_query_builder"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_logger"
)

// Injectors from wire.gen.go:

func NewApplication() (*app.Application, func(), error) {
	lState, cleanup := config.GetLuaState()
	backendList := config.GetBackendList(lState)
	backendFactory := logic_backend_factory.NewBackendFactory(backendList)
	queryBuilder := &logic_query_builder.QueryBuilder{}
	logParser := &logic_log_parser.LogParser{}
	service := &svc_logger.Service{
		BackendListConfig: backendList,
		BackendFactory:    backendFactory,
		QueryBuilder:      queryBuilder,
		LogParser:         logParser,
	}
	application := &app.Application{
		Logger: service,
	}
	return application, func() {
		cleanup()
	}, nil
}
