// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/Lofanmi/gobana/internal/app"
	"github.com/Lofanmi/gobana/internal/config"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_config"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_logger"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_lua_state"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_provider_factory"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_qq_wry"
	"github.com/Lofanmi/gobana/internal/svc_impls/svc_query_builder"
)

// Injectors from wire.gen.go:

func NewApplication() (*app.Application, func(), error) {
	application := config.GetConfigApplication()
	backends := config.GetConfigBackends()
	indexes := config.GetConfigIndexes()
	service := &svc_config.Service{
		Backends: backends,
		Indexes:  indexes,
	}
	providers := config.GetConfigProviders()
	providerFactory := &svc_provider_factory.ProviderFactory{
		Providers: providers,
	}
	queryBuilder := &svc_query_builder.QueryBuilder{
		ApplicationConfig: application,
		Backends:          backends,
		Indexes:           indexes,
	}
	qqWry := config.GetConfigQQWry()
	svc_qq_wryQQWry, err := svc_qq_wry.NewQQWry(qqWry)
	if err != nil {
		return nil, nil, err
	}
	luaState := &svc_lua_state.LuaState{
		QQWry: svc_qq_wryQQWry,
	}
	logParser := &svc_logger.LogParser{
		Backends: backends,
		LuaState: luaState,
	}
	aggregationParser := &svc_logger.AggregationParser{}
	svc_loggerService := &svc_logger.Service{
		Indexes:           indexes,
		Backends:          backends,
		ProviderFactory:   providerFactory,
		QueryBuilder:      queryBuilder,
		LogParser:         logParser,
		AggregationParser: aggregationParser,
	}
	appApplication := &app.Application{
		ConfigApplication: application,
		Config:            service,
		Logger:            svc_loggerService,
	}
	return appApplication, func() {
	}, nil
}
